core/urls.py
from django.urls import path
from .views import (
    HomeView,
    ItemDetailView,
    OrderSummaryView,
    CheckoutView,
    PaymentView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<slug>', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>', PaymentView.as_view(), name='payment')
]

crack_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" type="text/css" href="{% static '/css/all.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
	<title>CrackShop</title>
	{% block extra_head %}
	
	{% endblock extra_head %}
</head>
	<body>
		{% if messages %}
		{% for message in messages %}
		<div {% if message.tags %} class="d-inline-block rounded alert alert-{{ message.tags }}" {% endif %} role="alert">
			<span>{{ message }}</span>
		</div>
		{% endfor %}
		{% endif %}

		{% include 'header.html'%}

		{% block content %}
		{% endblock %}

		{% include 'footer.html' %}
		{% include 'scripts.html' %}
		{% block extra_scripts %}
		
		{% endblock extra_scripts %}
	</body>
</html>

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
 <main class="m-5 p-5">
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Checkout</button>
  </form>
</main>
{% endblock content %}

templates/footer.html
<footer class="text-white d-flex align-items-center fixed-bottom">
	&copy Ja, Ty i wszyscy razem <span class="">-BSP Twarze Ulicy</span>
</footer>

templates/header.html
{% load cart_template_tags %}
<header class="text-white d-flex align-items-center shadow-sm fixed-top">
	<div class="container">
		<div class="row">
			<div class="col d-flex align-items-center">
				<div class="logo p-2 rounded-lg d-inline-block">
					<a href="/">CrackShop</a>
				</div>
			</div>
			<div class="col-6 d-flex align-items-center">
				<div class="boxSearch p-1 rounded-pill">
					<input type="text" name="search" placeholder="Czego szukasz?" class="text-center text-white">
					<button type="submit" class="searchButton"><i class="fas fa-search"></i></button>
				</div>
			</div>
			<div class="col d-flex align-items-center">
				{% if request.user.is_authenticated %}
					<a href="{% url 'core:order-summary' %}" class="nav-link waves-effect btn btn-light mr-2">
					<span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
					<i class="fas fa-shopping-cart"></i>
					<span class="clearfix d-none d-sm-inline-block"> Cart </span>
					</a>
					<a href="{% url 'account_logout' %}">
						<button type="submit" class="btn btn-light float-right">Logout</button>
					</a>
				{% else %}
					<a href="{% url 'account_login' %}">
						<button type="submit" class="btn btn-light float-right">Login</button>
					</a>
					<a href="{% url 'account_signup' %}" class="ml-2">
						<button type="submit" class="btn btn-light float-right">Signup</button>
					</a>
				{% endif %}
			</div>
		</div>
	</div>
</header>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<main class="container mt-2">
		<div class="row mt-5">
{% for item in object_list %}

			<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 mt-5">
				<div class="product rounded p-4 shadow d-flex align-items-center" about="">
					<img src="{% static 'img/img.png' %}" class="imageProduct img-thumbnail float-left">
					<div class="productInfo d-inline-block text-white ml-3">
						<p class="rounded d-inline-block text-justify p-2 name"><a href="{{ item.get_absolute_url }}">{{ item }}</a></p><br>
						<p class="rounded d-inline-block text-justify p-2 price">
										{% if item.discount_price %}
											<del>{{ item.price }} PLN</del>
											{{ item.discount_price }} PLN
										{% else %}
											{{ item.price }} PLN
										{% endif %}</p><br>
						<p class="rounded d-inline-block text-justify p-2 seller mb-0">Annon69</p>
					</div>
					<span class="text-justify rate text-right text-white p-2 rounded">40% <i class="far fa-thumbs-up"></i></span>
				</div>
			</div>

    {% endfor %}
       		</div>
	</main>

{% endblock content %}

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}
{% block content %}
<br>
<br>
<main class="mt-5">
    <div class="container">
        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Item title</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total Item Price</th>
                </tr>
            </thead>
            <tbody>
                {% for order_item in object.items.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.item.title }}</td>
                    <td>{{ order_item.item.price }}</td>
                    <td>
                        <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                        {{ order_item.quantity }}  
                        <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                    </td>
                    <td>
                        {% if order_item.item.discount_price %}
                          {{ order_item.get_total_item_discount_price }}
                          <span class="badge badge-success">Saving: ${{ order_item.get_amount_saved }}</span>
                        {% else %}
                        {{ order_item.get_total_item_price }}
                        {% endif %}
                        <a href="{% url 'core:remove-from-cart' order_item.item.slug %}"><i style="color: red;"class="fas fa-trash-alt float-right"></i></a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5"> Your cart is empty</td>
                </tr>
                <tr>
                    <td colspan="5">
                      <a class="btn btn-primary float-right" href = "/">Back to shopping</a>
                    </td>
                </tr>
                {% endfor %}
                {% if object.get_total %}
                <tr>
                    <td colspan="4"><b>Order Total</b></td>
                    <td>{{ object.get_total }}<span class="badge badge-success ml-2">Saving: ${{ object.get_total_amount_saved }}</span></td>
                </tr>
                <tr>
                    <td colspan="5">
                    <a class="btn btn-warning float-right" href = "/checkout/">Proceed to checkout</a>
                    <a class="btn btn-primary float-right mr-2" href = "/">Back to shopping</a>
                </td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</main> 
{% endblock content %}

templates/payment.html
{% extends "base.html" %}

{% block extra_head %}
<style>

#stripeBtnLabel {
  font-family: "Helvetica Neue", Helvetica, sans-serif;
  font-size: 16px;
  font-variant: normal;
  padding: 0;
  margin: 0;
  -webkit-font-smoothing: antialiased;
  font-weight: 500;
  display: block;
}

#stripeBtn {
  border: none;
  border-radius: 4px;
  outline: none;
  text-decoration: none;
  color: #fff;
  background: #32325d;
  white-space: nowrap;
  display: inline-block;
  height: 40px;
  line-height: 40px;
  box-shadow: 0 4px 6px rgba(50, 50, 93, .11), 0 1px 3px rgba(0, 0, 0, .08);
  border-radius: 4px;
  font-size: 15px;
  font-weight: 600;
  letter-spacing: 0.025em;
  text-decoration: none;
  -webkit-transition: all 150ms ease;
  transition: all 150ms ease;
  float: left;
  width: 100%
}

button:hover {
  transform: translateY(-1px);
  box-shadow: 0 7px 14px rgba(50, 50, 93, .10), 0 3px 6px rgba(0, 0, 0, .08);
  background-color: #43458b;
}

.stripe-form {
  padding: 5px 30px;
}

#card-errors {
  height: 20px;
  padding: 4px 0;
  color: #fa755a;
}

.stripe-form-row {
  width: 100%;
  float: left;
  margin-top: 5px;
  margin-bottom: 5px;
}

/**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}

.current-card-form {
  display: none;
}

</style>
{% endblock extra_head %}

{% block content %}

  <main >
    <div class="container wow fadeIn pt-4">

      <h2 class="my-5 h2 text-center">Payment</h2>

      <div class="row">

        <div class="col-md-12 mb-4">
          <div class="card">

            {% if card %}
              <div style="padding: 5px 30px;">
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="use_default_card" id="use_default_card">
                  <label class="custom-control-label" for="use_default_card">Use default card:
                    **** **** **** {{ card.last4 }} 
                  <span>Exp: {{ card.exp_month }}/{{ card.exp_year }}</span></label>
                </div>
              </div>
            {% endif %}

            <div class="current-card-form">
              <form action="." method="post" class="stripe-form">
                  {% csrf_token %}
                  <input type="hidden" name="use_default" value="true">
                  <div class="stripe-form-row">
                    <button id="stripeBtn">Submit Payment</button>
                  </div>
                  <div id="card-errors" role="alert"></div>
              </form>
            </div>

            <div class="new-card-form">
              <form action="." method="post" class="stripe-form" id="stripe-form">
                  {% csrf_token %}
                  <div class="stripe-form-row" id="creditCard">
                      <label for="card-element" id="stripeBtnLabel">
                          Credit or debit card
                      </label>
                      <div id="card-element" class="StripeElement StripeElement--empty"><div class="__PrivateStripeElement" style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;"><iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame5" allowpaymentrequest="true" src="https://js.stripe.com/v3/elements-inner-card-19066928f2ed1ba3ffada645e45f5b50.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js&amp;controllerId=__privateStripeController1" title="Secure payment input frame" style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; height: 19.2px;"></iframe><input class="__PrivateStripeElement-input" aria-hidden="true" aria-label=" " autocomplete="false" maxlength="1" style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;"></div></div>
                  </div>
                  <div class="stripe-form-row">
                    <button id="stripeBtn">Submit Payment</button>
                  </div>
                  <div class="stripe-form-row">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" class="custom-control-input" name="save" id="save_card_info">
                      <label class="custom-control-label" for="save_card_info">Save for future purchases</label>
                    </div>
                  </div>
                  <div id="card-errors" role="alert"></div>
              </form>
            </div>

          </div>
        </div>

      </div>
      {% include "order_snippet.html" %}
    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}

<script src="https://js.stripe.com/v3/"></script>
<script nonce="">  // Create a Stripe client.
  var stripe = Stripe('{{STRIPE_PUBLIC_KEY}}');

  // Create an instance of Elements.
  var elements = stripe.elements();

  // Custom styling can be passed to options when creating an Element.
  // (Note that this demo uses a wider set of styles than the guide below.)
  var style = {
    base: {
      color: '#32325d',
      fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aab7c4'
      }
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
  };

  // Create an instance of the card Element.
  var card = elements.create('card', {style: style});

  // Add an instance of the card Element into the `card-element` <div>.
  card.mount('#card-element');

  // Handle real-time validation errors from the card Element.
  card.addEventListener('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });

  // Handle form submission.
  var form = document.getElementById('stripe-form');
  form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(card).then(function(result) {
      if (result.error) {
        // Inform the user if there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
      }
    });
  });

  // Submit the form with the token ID.
  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('stripe-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form
    form.submit();
  }

  var currentCardForm = $('.current-card-form');
  var newCardForm = $('.new-card-form');
  var use_default_card = document.querySelector("input[name=use_default_card]");
  use_default_card.addEventListener('change', function() {
    if (this.checked) {
      newCardForm.hide();
      currentCardForm.show()
    } else {
      newCardForm.show();
      currentCardForm.hide()
    }
  })

</script>

{% endblock extra_scripts %}

templates/product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
     <link rel="stylesheet" type="text/css" href="{% static '/css/product.css' %}">

     <div class="container">
          <div class="row product-con p-5 rounded">
               <div class="col">
                    <img src="{% static 'img/img.png' %}" class="img-thumbnail product-con-img">
               </div>
               <div class="col text-white text-center">
                    <h2>{{ object.title }}</h2>
                    <h4>Price: 
                         {% if object.discount_price %}
                              <del>{{ object.discount_price }} PLN</del>
                              {{ object.price }} PLN
                         {% else %}
                              {{ object.price }} PLN
                         {% endif %}
                    </h4>

                    <span class="text-justify text-right text-white p-2 rounded">40% <i class="far fa-thumbs-up"></i></span>

                    <div class="mt-5">
                         <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">Add to cart</a>
                         <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">Remove from cart</a>
                    </div>
               </div>  
          </div>

          <div class="row product-con p-5 rounded">
               <div class="col text-white">
                    <h4>{{ object.description }}</h4>
               </div>
          </div>
     </div>

     

{% endblock content %}

templates/scripts.html
	{% load static %}
    <script type="text/javascript" src="{% static '/js/jQuery.min.js' %}"></script>
	<script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>